name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting (if available)
        run: npm run lint --if-present

      - name: Run tests (if available)
        run: npm test --if-present

      - name: Build plugin
        run: npm run build

      - name: Verify build output
        run: |
          echo "Checking build output..."
          if [ -d ".medusa/server" ]; then
            echo "✅ Build output found"
            ls -la .medusa/server/
          else
            echo "❌ Build output missing"
            exit 1
          fi

  validate-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Validate package.json
        run: |
          echo "Validating package.json..."
          npm pkg get name
          npm pkg get version
          npm pkg get main
          
      - name: Check for required files
        run: |
          echo "Checking required files..."
          [ -f "README.md" ] && echo "✅ README.md exists" || echo "❌ README.md missing"
          [ -f "package.json" ] && echo "✅ package.json exists" || echo "❌ package.json missing"
          [ -f "src/index.ts" ] && echo "✅ src/index.ts exists" || echo "❌ src/index.ts missing"

      - name: Dry run publish
        run: npm publish --dry-run
